version: "3.5"
services:
  plex:
    environment:
      - LETSENCRYPT_HOST=${PLEX_HOST}
      - VIRTUAL_HOST=${PLEX_HOST}
      - VIRTUAL_PORT=32400
    networks:
      - external-network

networks:
  external-network:
    external:
      name: ${LETSENCRYPT_NGINX_PROXY_COMPANION_NETWORK}
