version: "3.5"
services:
  plex:
    container_name: ${PLEXFLIX_PROJECT_NAME}-plex
    environment:
      - PUID=${PLEXFLIX_USER}
      - PGID=${PLEXFLIX_GROUP}
      - VERSION=docker
    image: linuxserver/plex:latest
    networks:
      - plexflix
    ports:
      - ${PLEX_DLNA_SERVER_TCP_PORT}:32469
      - ${PLEX_DLNA_SERVER_UDP_PORT}:1900
      - ${PLEX_MEDIA_SERVER_PORT}:32400
      - ${PLEX_NETWORK_DISCOVERY_PORT_1}:32410
      - ${PLEX_NETWORK_DISCOVERY_PORT_2}:32412
      - ${PLEX_NETWORK_DISCOVERY_PORT_3}:32413
      - ${PLEX_NETWORK_DISCOVERY_PORT_4}:32414
      - ${PLEX_ROKU_COMPANION_PORT}:8324
    restart: unless-stopped
    volumes:
      - ${PLEX_CONFIG_PATH}:/config:delegated
      - ${PLEXFLIX_LIBRARIES_MOUNT_PATH}:/libraries:shared
