version: "3.5"
services:
  plexdrive:
    build:
      context: ./plexdrive
    cap_add:
      - MKNOD
      - SYS_ADMIN
    container_name: ${PROJECT_NAME}-plexdrive
    devices:
      - /dev/fuse
    environment:
      - PUID=${USER}
      - PGID=${GROUP}
      - ROOT_FOLDER_ID=${PLEXDRIVE_ROOT_FOLDER_ID}
    healthcheck:
      test: "[ -f /data/.mountcheck ] && exit 0 || exit 1"
      interval: 10s
      timeout: 10s
      start_period: 10s
    image: ${PROJECT_NAME}/plexdrive:latest
    networks:
      - plexflix
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
    volumes:
      - ${PLEXDRIVE_CONFIG_PATH}:/config:delegated
      - ${LIBRARIES_MOUNT_PATH}:/data:shared
